
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAREN_IZQ = 11;
  public static final int ASTERISCO = 7;
  public static final int COMA = 6;
  public static final int PAREN_DER = 12;
  public static final int LETRA = 8;
  public static final int ENTERO = 3;
  public static final int EOF = 0;
  public static final int MAS = 9;
  public static final int ID = 2;
  public static final int TIPO = 10;
  public static final int IGUAL = 4;
  public static final int error = 1;
  public static final int PUNTOYCOMA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "IGUAL",
  "PUNTOYCOMA",
  "COMA",
  "ASTERISCO",
  "LETRA",
  "MAS",
  "TIPO",
  "PAREN_IZQ",
  "PAREN_DER"
  };
}

