
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAREN_IZQ = 15;
  public static final int COMA = 13;
  public static final int DECIMAL = 3;
  public static final int ASTERISCO = 6;
  public static final int POTENCIA = 9;
  public static final int PAREN_DER = 16;
  public static final int LETRA = 4;
  public static final int ENTERO = 2;
  public static final int EOF = 0;
  public static final int MAS = 7;
  public static final int ID = 10;
  public static final int TIPO = 14;
  public static final int IGUAL = 11;
  public static final int error = 1;
  public static final int DIVISION = 8;
  public static final int PUNTOYCOMA = 12;
  public static final int RESTA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "DECIMAL",
  "LETRA",
  "RESTA",
  "ASTERISCO",
  "MAS",
  "DIVISION",
  "POTENCIA",
  "ID",
  "IGUAL",
  "PUNTOYCOMA",
  "COMA",
  "TIPO",
  "PAREN_IZQ",
  "PAREN_DER"
  };
}

